---
# tasks file for ansible-elastic-baremetal

- include_tasks: elastic_baremetal_pre_install.yml
  tags:
    - elastic_baremetal-pre-install

- include_tasks: elastic_baremetal_install.yml
  loop: "{{ aeb_storage_paths }}"
  tags:
    - elastic_baremetal-install

- include_tasks: elastic_baremetal_post_install.yml
  loop: "{{ aeb_storage_paths }}"
  tags:
    - elastic_baremetal-post-install

- include_tasks: elastic_baremetal_post_install_monitoring.yml
  tags:
    - elastic_baremetal-post-install
